### ISSUE TITLE
which kit should I buy in order to reproduce this repository?

### ISSUE THREAD

**Issue by liubenyuan** [RISCV-on-Microsemi-FPGA/M2S025-Creative-Board#6]

**Comment by CLappin** [comment]
Hi,

The SmartFusion2 version of Futures Creative Board is no longer available via their website.
There is an IGLOO2 version of this board which the project in [this](https://github.com/RISCV-on-Microsemi-FPGA/RISC-V-Creative-Board) repository  can be used.  It is effectively the same design with some minor modification to work on the IGLOO2 board.
This board is available from this [link](https://www.futureelectronics.com/p/development-tools--development-tool-hardware/futurem2gl-evb-microsemi-7075272)


Regards,
Ciaran

**Comment by liubenyuan** [comment]
Thanks!

**Comment by CLappin** [comment]
HI,

After a bit of searching a managed to find a link if your still interested in the SmartFusion2 board. 
[SF2](https://www.futureelectronics.com/p/development-tools--development-tool-hardware/futurem2sf-evb-future-electronics-dev-tools-3091560)

If you are working on RISC-V I would recommend  using the Igloo2 board as it is less hassle.

Thanks ,
Ciaran

**Comment by salmansheikh** [comment]
Is the SF2 board more of a hassle because of the Cortex-M3 and the bootloader?
